# @package _group_

nq_table_test:
  _target_: dpr.data.retriever_data.JsonlQASrcTable
  file: "/mnt/zhiruow/hitab/table-retrieval/datasets/nq_table/test.jsonl"

nq_table_dev:
  _target_: dpr.data.retriever_data.JsonlQASrcTable
  file: "/mnt/zhiruow/hitab/table-retrieval/datasets/nq_table/dev.jsonl"

nq_table_train:
  _target_: dpr.data.retriever_data.JsonlQASrcTable
  file: "/mnt/zhiruow/hitab/table-retrieval/datasets/nq_table/train.jsonl"